default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: bookroom_development
  username: root
  password: password
  host: localhost

test:
  <<: *default
  database: bookroom_test
  username: root
  password: password
  host: localhost

