~
default: &default
# adapter: sqlite3
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
# timeout: 5000

development:
  <<: *default
# database: db/development.sqlite3
  database: app_development

test:
  <<: *default
# database: db/test.sqlite3
  database: app_test

# production:
# <<: *default
# adapter: postgresql
# encoding: unicode
# url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: <%= ENV['MYSQL_NAME'] %>
  username: myuser
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOST'] %>
  
